using System;
using Microsoft.EntityFrameworkCore.Migrations;

/// <summary>
/// the long 2022 is the date we created, alongside that is the name we put in the command line, the number stamp keeps the files in order when its applied, the folder Migrations and classes within in sln explorer was created using this command
/// partial class allows you to makes changes without losing what you changed when this generated class gets regenerated
/// </summary>
namespace EntityFrameworkCore_Tutorial.Migrations
{
    public partial class Initialization : Migration
    {
        /// <summary>
        /// up method creates the customer table for us, which forwards the database
        /// customers in up is the name we put in the db command line
        /// id is autogenerated for and was set as primary key
        /// </summary>
        /// <param name="migrationBuilder"></param>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Active = table.Column<bool>(type: "bit", nullable: false),
                    Sales = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Updated = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customers", x => x.Id);
                });
        }

        /// <summary>
        /// the down reverses what the up does, which deletes the database
        /// </summary>
        /// <param name="migrationBuilder"></param>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Customers");
        }
    }
}
